language: java
dist: trusty
sudo: required
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
before_install:
- docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
- sh install_setup_kubernetes.sh
- cat ${HOME}/.kube/config | grep name | grep admin | rev
- kubectl get nodes
