language: java
dist: trusty
sudo: required
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
before_script: echo $TEST2
env:
  global:
    secure: VhC4dj6DI8e3taIgdISmFg79lkuy9S97a10BNBvR2lcctERX127lCe8NdWzkP+GmjsluMrp4gpc1eU8/+aiyIi4Lzaz3loGcq9qJdLTEoXuHdPz/TqvDmNQ1PfOg9NgFEdWIhumjJAkh47R3mKUPovz1hv/gvGz7BsBgCWMHkwxpEowsr/wv0sTDpItFN3V/CFK2D0Tb2eFg5+/rdDq5pOwalbr7MeBsWAc6EwRdGQXaraWGI1MTIhvvU1TM5Z5jSySLbQcihocZczh/fNjR1rD9QYYGOWeGSdGbHXzOaxA3WRDjvHgbP3CGlwHvXycJr/w1NcqGHMt3Fg72TO5izotjQYmwcV8vI2wdzKB7jcv3jeu6Der+m5oVosYJwNDI2LHFH+rj367uQSqJ4HUVTWKRlna2jfK6bOdDUqFkXzvWiH5WbNd/gSP2EHXlDjcYQKYTarOWDkTW9/tFtdH7ubObMb6QQBRXN/eF3ykeepxhiiw/r5hHsqPPPf5fai0CbyFIAs8frzsZc9JfAol8v8kaWzHBvW6rDvaU4jLGoUiwT1n/9txq5Ka8gXY8jE6Jybn9hhDQZoe+abySo/J/AekU47igEnFkv18vV5Nte2lOF2kvzn6yIRM+cNxjDoZKQl4QrNmzsMaw6/j5uCNsamiImu1WjbvH74YNWMMsryQ=
