language: java
dist: trusty
sudo: required
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
before_install:
- openssl aes-256-cbc -K $encrypted_b65a1db2d286_key -iv $encrypted_b65a1db2d286_iv -in travis.secrets.enc -out travis.secrets -d
- cat travis.secrets
- source travis.secrets
- echo ${A_TEST}
- docker pull ${IMAGE_NAME}