language: java
dist: trusty
sudo: required

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - docker build -t quantum/quantum .
  - echo I should be pushing the image to somewhere.

deploy:
  - provider: script
    script: echo deploying $TRAVIS_BRANCH (Pull request -> $TRAVIS_PULL_REQUEST)
    on:
      branch: master
  - provider: script
    script: echo deploying $TRAVIS_BRANCH (Pull request -> $TRAVIS_PULL_REQUEST)
    on:
      branch: release
