language: java
dist: trusty
sudo: required

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script: ./install_setup_kubernetes.sh "$TEST2"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - echo "$TEST"
  - echo "${DOCKER_REGISTRY}/quantum"
  - sh install_setup_kubernetes.sh $TEST
  - docker build -t "${DOCKER_REGISTRY}/quantum"
  - docker login -u="${DOCKER_USERNAME}" -p="fakepassword" ${DOCKER_REGISTRY}
  - kubectl get nodes
  - echo I should be pushing the image to somewhere.

deploy:
  - provider: script
    skip_cleanup: true
    script: 
      - echo "deploying $TRAVIS_BRANCH (Pull request -> $TRAVIS_PULL_REQUEST)"
    on:
      branch: master
  - provider: script
    script: 
      - echo "deploying $TRAVIS_BRANCH (Pull request -> $TRAVIS_PULL_REQUEST)"
    on:
      branch: release
