language: java
dist: trusty
sudo: required
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
before_script: echo "Test secret in settings:" $TEST1 "Test secret from file:" $TEST2
env:
  global:
    secure: f4q8J8SfigKzv5zN2IZ86W6qZ2LDouWpd4taCJgaYwGa26/yqKklafK8YNKyP1wxApwcPXVNKHwhibFv1J2cWB1U9Z8vXjPAZHeynayI/I3G+3WvNmK8AzG7gYEGs0lrjUQMYkZdtQwNycucPrxHIhd1B61eFoBXQZ22oZlmXEjTLkYGRroeGsxJ4v0SecQAli8ha4ZH3N7uDo5KW72XVfrCfY0eYaRoQ0iLCZywGx1U9yQWVmGNq2XzpZEoz4XL0DonMt9NaxbVlfJExnIzs4elGI+u1dl1Z7v5f+NPCli/rO4ea8cAdpy3bp6blPFBFX3+7XKKGpWkRJMJkSaLjnUsywdaN7dVl5IznuceduhEejaR0WfMXjuf1NviOU7zOopJEA8VtmfrcVcCyH9k0I4yZ6jU0LvUdvQBAy/ahOaR/aIsPqlW8GeWf7fl3neOcNzpXM0PCOw4vGk9aDs6ZnImObUy8E1nUoG//PdOqS7N4weaN1QW9hOhumf8EB/N894RQmxa+3oibijxcac3CiLC8S97oR9JINBkRsQIwGIjhEo8LkZMnb/sX1cnuCA6Ce9jIZf8utTU6lxJKSLvLHkDzBZ4MEKInTfJwF4YbMwbTd3vm8blEW0qLWZIudyU5XSrGx84cg8xB0SwP6wsftnxKwvX8YKUdnl2xgGLCVk=
