language: java
dist: trusty
sudo: required
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- ./scripts/setup_kubernetes.sh ${TRAVIS_BRANCH}
- kubectl get nodes
deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy.sh ${TRAVIS_BRANCH}
    on:
      branch: master
  - provider: script
    script: ./scripts/deploy.sh ${TRAVIS_BRANCH}
    on:
      branch: release