language: java
dist: trusty
sudo: required
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
before_script: echo $TEST2
env:
  global:
    secure: lsiTskXsX7NfmMfeO3Y/AREzSU6uLdweYCWGKY62hJle4Bz+Tr5fLPxO5LQFD+BmemwqJAEFBmSQvqjCHvIK7F4NlY3d1WTfFMEaaloHHrE2u1e0QdMGN9Z/RATwqX3NxcD66zzgIpdAYs+lWZy4Q++bTCjSe43OinqTpkW9hRJa0Iu91Q5WO7UtpWyos5zf3yG4EF4B/v9PxWDlPdd2KOm8EfDzPU+rzEqy7/sGGYdGmPUOcbwuh2MPPrGfwsfKfqYTvc1URIbEGSI2BJrfmA1Da3JbfO/uh8jw22VST8Igr/ElRSZM5184gE/1xqy7GOLFSg0ZiKuFBBYYJkIKUp3cl57ZibJJIgdaqNGDh9EY4+Yxvvb6aqAK4uDojeyQ88zTU2en1CO2bpwtFY+0M5VwqmnicKGS/mWIlHuBiSRyTLMnG7W6+5IAeEwuyr+RYqOHsS4WglWsNs/mD3e2hhqoComWIavCN4e1Ak4vGDtcyqwgm+/HyHUmk1UlYb89XbBefdYkTCuK2Z//O6LS2vo/mnvkKqsTcA+uNSf5NBH+4v6HnQRSgRdjiHXQKJbA2CbQGQ4cheIY2Qfun7h/tK7Fq74rddxW68wOz7XKu2Tcg/0qGvy3PcpQqkfEqjQH31aWLv68GDAiI2h86EbbjzJTS5KNyrn7yNHJpZ5otf0=
